### ISSUE TITLE
Add data to existing data for compatible fields

### ISSUE THREAD

**Issue by johankees** [jenkinsci/jira-steps-plugin#10]
Hi,

Would be nice if we can add data, not just edit/update. For example, being able to add a label, without having to fetch the existing labels (if possible) and adding in the pipeline script.

For example when we have:
labels: build_1, build_2
I would like to be able to add a new label without removing existing entries.

This is similar to what we can do for comments.

**Comment by nrayapati** [comment]
Yes, it would nice if we can have these kind of steps to avoid some boilerplate. I will think of adding couple of steps around editing issues in near future like addIssueLabel, addIssueFixVersion and so on. Thanks for reporting. 

or we could achieve this by writing some basic code as follows: 

```groovy
      def result = jiraGetIssue idOrKey: "TEST-01"
      def newlabels = result.data.fields.labels << "newlabel"
      def testIssue = [fields: [labels: newlabels]]
      response = jiraEditIssue idOrKey: "TEST-01", issue: testIssue
```

**Comment by nrayapati** [comment]
@johankees were you able to test above example, I have corrected it after testing.

**Comment by johankees** [comment]
Haven't had time to test this. Will do this this week and get back to you.

**Comment by johankees** [comment]
The mentioned code works fine. No issues found. Would be great if some of the boilerplate could be removed indeed. Thanks Naresh. Your work is much appriciated

**Comment by nrayapati** [comment]
@johankees I have added TODO to the project plan, soon once I have some time will work on it. Thanks for reporting. Closing this.
