### ISSUE TITLE
Retrieve issues mentioned in commits

### ISSUE THREAD

**Issue by akbertram** [jenkinsci/jira-steps-plugin#13]
This is a great project! I'm not sure if this is a missing feature or if I just don't understand, but is it possible to retrieve issues that are mentioned in the commits? For example, transition all issues mentioned in the changelog for this build to "Staged for Release" ?

**Comment by rafi-whipclip** [comment]
+1

**Comment by nrayapati** [comment]
It is possible to transition the issue once we have enough input.  For more information about that jira step at [1]. But to retrieve that information from commit or changelog is not part of this plugin probably we should refer to the appropriate plugin like git, github, gitlab or some other scm plugin. 

Hope the above explanation is useful. 

[1] https://jenkinsci.github.io/jira-steps-plugin/jira_transition_issue.html

**Comment by nrayapati** [comment]
@akbertram do you have any further thoughts on this?

**Comment by akbertram** [comment]
Well, I understand what you're saying, but I still think this is a missing feature, and it's keeping us from moving from the jira-ext-plugin.

The SCM plugins probably provide a way to obtain the change log, but it still needs to be parsed for JIRA keys, which would be nice to have in this plugin.

**Comment by nrayapati** [comment]
Once we have an commit message or change log, it would be like writing some groovy code to parse  the string get that information (like string parsing or regex parsing). I guess that doesn't need to be in this plugin, it can live in one of your shared libraries. 

Hope I understand your problem correctly.

**Comment by nrayapati** [comment]
@akbertram I am closing this issue for now (in fact closing the future support to log more issues here, is to follow the standard Jenkins practice), hope I have answered your question. In case if you need more information please log a JIRA to the Jenkins queue[1]. Thanks. 

[1] https://issues.jenkins-ci.org/browse/JENKINS-44400?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20jira-steps-plugin
