### ISSUE TITLE
Add a comment takes [~anonymous] as user 

### ISSUE THREAD

**Issue by wcd923** [jenkinsci/jira-steps-plugin#14]
Hi,

Either this is a bug or I don't know how to configure this field. 

Context: When updating a issue with a commit that contains the issue ID (on a Bitbucket repo that has hooks enabled) I get this comment: (e.g):

 _Job name: jenkins-jira with build number: 97 finished with status: SUCCESS. Go to http://127.0.0.1:8080/job/jenkins-jira/97/_

> _Automatically created by: **[~anonymous]** from Build URL_  

The portion of the pipeline:

`jiraAddComment (
                site: "${JIRA_SITE}",
                idOrKey: "${JIRA_ISSUE}",
                comment: "Job name: ${env.JOB_NAME} with build number: ${env.BUILD_NUMBER} finished   with status: ${currentBuild.result}. Go to ${env.BUILD_URL} "
        )`

_Jira Server on-premise 7.0.10
Jenkins ver. 2.19.3
jira-steps ver 1.0.1
I'm using basic authentication intead of OAuth_

I think, there is an issue already about this somewhere on the Internet but I could not find it. 
 What user should be printing, the one who committed the code and triggered the build job or the Jenkins user? 

Could you please assist me with this?

**Comment by wcd923** [comment]
I forgot to mention, I'm using basic authentication intead of OAuth.

**Comment by nrayapati** [comment]
The user name being printed there is the actual user (BUILD_USER) being logged in to the Jenkins instance, but not the JIRA user being configured. it is defaulted to `anonymous`[1] when no one logged in. Hope this explanation helps. 

[1] https://github.com/jenkinsci/jira-steps-plugin/blob/master/src/main/java/org/thoughtslive/jenkins/plugins/jira/util/JiraStepExecution.java#L133

**Comment by wcd923** [comment]
Is there a way to overwrite/edit that value within the Jenkinsfile?
Could you please provide it? As I am not able to overwrite BUILD_USER (I did not find a way to accomplish this yet, perhaps you know how to do this) I'd like to print the name of the commit's author when there is no one logged in and build had been triggerd by a hook.

**Comment by nrayapati** [comment]
I don't think we can override the BUILD_USER manually per my knowledge. 

Motive behind printing that audit log was to identify the build url and the actual person who build that job, if we wanted to print more information (like in your case commit user) you could always enhance the commit message to include more details. 

Printing the JIRA User being configured in Jenkins would a redundant/duplicate as the comment is made by that user already. 

Like: 
> Job name: jenkins-jira with build number: 97 finished with status: SUCCESS. Go to http://127.0.0.1:8080/job/jenkins-jira/97/
COMMIT_USER: JENKINS/ACTUALUSER
Automatically created by: [~anonymous] from Build URL
> 

For remote trigger cases like hooks / timers, the user name should be either timer/system I guess, I will have to double check on that to see if it is anonymous.

**Comment by nrayapati** [comment]
Hope above explanation was helpful. Closing this issue, please log an JIRA if you need any further help with this. I will be closing the github issues support to follow the standard Jenkins practice.
