### ISSUE TITLE
Сan't create an issue with a component

### ISSUE THREAD

**Issue by maksim77** [jenkinsci/jira-steps-plugin#20]
Thanks for the release. But unfortunately it is not fixed all our problems.

1.  The method does not return an object "component" suitable for use on, instead it only returns a wrapper around the API. So before you can use it for example when you create a new issue it is necessary to call his field data.

```groovy
def component = jiraGetComponent id: '10100', site: "JIRA"
def testIssue = [fields: [ project: [id: 10105],
                         summary: "New JIRA Created from Jenkins.",
                         description: "New JIRA Created from Jenkins.",
                         components: component.data,
                         issuetype: [id: 10108]]]

response = jiraNewIssue issue: testIssue, site: "JIRA"
```

2. But it's not a problem :) The problem is that when trying to create an issue an error is returned:
https://pastebin.com/gggyTGS3

**Comment by nrayapati** [comment]
1. Each step return a common response, which has an extra information along with data. 
Please refer to the https://jenkinsci.github.io/jira-steps-plugin/config.html#error-handling. 
Documentation around this needs some improvement :).

2. `components` is list of components but you are sending just single one. Change that to be a list. 
```groovy
components: [component.data]
```

**Comment by maksim77** [comment]
Thanks for the clarification! Everything works fine!
