### ISSUE TITLE
Is there a way to specify a component for a new issue?

### ISSUE THREAD

**Issue by alvin-huang** [jenkinsci/jira-steps-plugin#21]
In our JIRA we require the parameter of 'components' to be set. However, I tried building the object with something like: `components: [Component[id: 123]]` and that didn't seem to work. The examples all show string/ID parameters like project id, summary, description, etc. while there can be multiple components so JIRA accepts a list of hashes instead. Is this possible with the jiraNewIssue call?

**Comment by nrayapati** [comment]
It is all groovy, it should just as simple as we define any object. I haven't tested the below example but it could be useful. Thanks.

```groovy
def component = [ name: "test-component",
                      description: "desc",
                      project: "TEST" ]

def testIssue = [fields: [ project: [id: 10000],
                          summary: "New JIRA Created from Jenkins.",
                          description: "New JIRA Created from Jenkins.",
                          components: [component],
                          issuetype: [id: 10000]]]

response = jiraNewIssue issue: testIssue
```

**Comment by nrayapati** [comment]
For more information about these input or other DTOs please refer to the classes under https://github.com/jenkinsci/jira-steps-plugin/tree/master/src/main/java/org/thoughtslive/jenkins/plugins/jira/api

**Comment by maksim77** [comment]
@alvin-huang or you can get the object "component" perform another step.
```groovy
def component = jiraGetComponent id: '123'
```
And use it further as a list item when creating a new issue.

**Comment by alvin-huang** [comment]
Thanks to both of you @nrayapati @maksim77, I was just building the component object wrong.
