### ISSUE TITLE
Problem in Creating a new Issue during the pipeline run

### ISSUE THREAD

**Issue by bharathijo** [jenkinsci/jira-steps-plugin#22]
I tried your documentation to create a new issue during the pipeline run. It's is constantly failing not creating an Issue. It would be great if you can help me with it.

**Comment by nrayapati** [comment]
How could anyone can help with such a generic statement?

**Comment by alvin-huang** [comment]
I previously got errors where the example was showing `project: [id: '10000']` but Jenkins was looking for id to be an int so removing the quotes fixed this. @bharathijo was this the same thing you were seeing?

**Comment by bharathijo** [comment]
Thanks for that alvin-huang. I will check it out.

**Comment by nrayapati** [comment]
Thanks @alvin-huang for pointing that out, I will fix those documentation error.

**Comment by maksim77** [comment]
@alvin-huang 👍. I'm not a contributor or maintainer in this project but please do it :-)

**Comment by bharathijo** [comment]
@alvin-huang, that was helpful.

**Comment by bharathijo** [comment]
@nrayapati . After making the modification I was successfully able to create a new issues. But I have trouble in figuring out in setting up priority, Assignee, Comments section for the  same issue. Please help

**Comment by alvin-huang** [comment]
@bharathijo look through the pipeline steps outlined in the wiki: https://jenkinsci.github.io/jira-steps-plugin/jira_assign_issue.html, it has good examples of how to do the things you have listed.

**Comment by nrayapati** [comment]
@alvin-huang Thanks for your inputs here. 

@bharathijo as @alvin-huang suggested please refer to the documentation over the wiki[1] for more information or guidance. and also the code is pretty straight forward in case if any in detailed information. 

And it would be easy to answer quickly if you can be more specific with your use case along with the code if any that you are trying. Thanks for reporting though. 

[1] https://jenkinsci.github.io/jira-steps-plugin/jira_get_component.html

**Comment by nrayapati** [comment]
@alvin-huang  About `id` type consistency, there was this issue[#3] with serialization a while ago I had to change all those ids to strings, but I missed making that change across, it was my bad. 

I have already made those changes locally, but I couldn't merge those in as I was away on vacation for about a month long, now I am back :), should be able to merge those in soon after testing. 

Thanks again .

**Comment by nrayapati** [comment]
@bharathijo Hope your issue got resolved, closing this issue feel free to log a JIRA instead if there are any further issues, soon I am going to disable the support of logging issues here at github to follow the jenkins standard practice. Thanks for reporting.
