### ISSUE TITLE
editIssue: please improve documentation (how to add a label)

### ISSUE THREAD

**Issue by cpolzer** [jenkinsci/jira-steps-plugin#23]
Hi!

I have been breaking my brain about how to simply update the labels of an issue by appending one?

**Comment by cpolzer** [comment]
Just to be complete. 
This is the pipeline, first fetching the issue, then appending a label and then trying to update:
 ```
stage("testing to update jira task"){
       
            def id = "Test-01"
            def issue = jiraGetIssue idOrKey: id
            echo  "issue's labels: " + issue.data.fields.labels.join("\n")
            issue.data.fields.labels.add("Q-Keyc")
            echo  "Edit issue's labels: " + issue.data.fields.labels.join("\n")

            jiraEditIssue idOrKey: id, issue: issue

    }
```
Exception is then: 
`Caused by: java.lang.ClassCastException: org.thoughtslive.jenkins.plugins.jira.steps.EditIssueStep.issue expects class org.thoughtslive.jenkins.plugins.jira.api.input.IssueInput but received class org.thoughtslive.jenkins.plugins.jira.api.ResponseData`

**Comment by maksim77** [comment]
Try:
```
stage("testing to update jira task"){
      
           def id = "Test-01"
           def issue = jiraGetIssue idOrKey: id
           echo  "issue's labels: " + issue.data.fields.labels.join("\n")
           issue.data.fields.labels.add("NewLabel")
           echo  "Edit issue's labels: " + issue.data.fields.labels.join("\n")

           jiraEditIssue idOrKey: id, issue: issue.data

   }
```

**Comment by cpolzer** [comment]
I tried, now i get this exception:

`java.lang.ClassCastException: org.thoughtslive.jenkins.plugins.jira.steps.EditIssueStep.issue expects class org.thoughtslive.jenkins.plugins.jira.api.input.IssueInput but received class org.thoughtslive.jenkins.plugins.jira.api.Issue`

**Comment by cpolzer** [comment]
Also tried passing an IssueInput

```
def issueinput = new IssueInput() 
issueInput.fields = issue.data.fields
```

-> then Exception is that Class FieldsInput would have been expected. 
Not sure about the relation of FieldsInput and Fields here. Could Fields not just extend FieldsInput so this would be  working?

**Comment by nrayapati** [comment]
While creating or updating, JIRA allows only few fields/properties so we had to divide on what we can send and query, hence there are two objects `Issue` and `IssueInput` and also other related objects like FieldsInput. There are few type differences between fields and fieldsInput, let me see if we can extend fields without breaking existing code. 

Try something similar to the example of appending fixed versions. https://jenkinsci.github.io/jira-steps-plugin/common_usages.html#append-new-fix-version-to-existing-issue

```groovy
node {
  stage('JIRA') {
      def issue = jiraGetIssue idOrKey: "TEST-01"
      def newLabels = result.data.fields.labels << "new label"
      def testIssue = [fields: [labels: newLabels]]
      response = jiraEditIssue idOrKey: "TEST-01", issue: testIssue
  }
}
```

**Comment by nrayapati** [comment]
This comment on other issue can also be useful 
https://github.com/jenkinsci/jira-steps-plugin/issues/10#issuecomment-292766316

I have started putting some examples in the documentation, but it needs some improvement. Thanks.

**Comment by nrayapati** [comment]
Thanks for input @maksim77

**Comment by cpolzer** [comment]
@nrayapati your example worked, thx a lot!

**Comment by nrayapati** [comment]
@cpolzer Thanks for the confirmation, closing this since the example is working. There is TODO in project notes to improve the documentation, I will log a JIRA for that soon. Thanks again.
