### ISSUE TITLE
jiraAddComment seems to break out of for loop?

### ISSUE THREAD

**Issue by emeagher** [jenkinsci/jira-steps-plugin#6]
When I call this function:

```
@NonCPS
def commentOnJiraIssues(jiraKeys, comment) {
  if (jiraKeys) {
      for (i = 0; i < jiraKeys.size(); i++) {
        jiraAddComment site: "LOCAL", idOrKey: jiraKeys[i], comment: comment.replaceAll('%2F', '/'), failOnError: false
      }
    }
}
```

From within a declarative pipeline, it never gets past the first key in `jiraKeys`. If I put an `echo` statement after the `jiraAddComment` it never prints.

I'm using Jenkins 2.32.3, JIRA Pipeline Steps v1.0.1 and my Jira server is v7.3.0#73011-sha1:3c73d0e (On premise).

**Comment by nrayapati** [comment]
@emeagher I wouldn't try calling pipeline steps in a method with @NonCPS annotation, try removing that annotation from the function signature.

**Comment by nrayapati** [comment]
Refer to the more documentation about ```@NonCPS``` at https://github.com/jenkinsci/workflow-cps-plugin/blob/master/README.md#technical-design

**Comment by emeagher** [comment]
Thank you Naresh. I will try that and get back to you.

**Comment by emeagher** [comment]
Removing the @NonCPS annotation worked. Thank you for pointing that out!

**Comment by nrayapati** [comment]
Welcome! @emeagher
