### ISSUE TITLE
Assign User by E-Mail

### ISSUE THREAD

**Issue by tschechniker** [jenkinsci/jira-steps-plugin#7]
Hi,

would there be a way to assign a sser by his e-mail address?
```java
def issue = [fields: [ project: [id: 1234],
                                                 summary: "Error",
                                                 description: "test",
                                                 assignee: [emailAddress: 'test@example.de'],
                                                 issuetype: [id: 1]]]
```

Currently i'm getting this error:

Error Message: {"errorMessages":[],"errors":{"assignee":"expected Object containing a 'name' property"}}

**Comment by nrayapati** [comment]
@tschechniker The error message printed above is from JIRA itself, so the name is mandatory field while updating issue. There is no way that we can change that behavior.  

But we can add a new step called `jiraUserSearch`, which will allow us to query users by email address then we can use the name from the results to update issue. 

it will be something like:
```groovy
def user = jiraUserSearch input: 'test@example.de'
def userName = user.data.name

def issue = [fields: [ project: [id: 1234],
                       summary: "Error",
                       description: "test",
                       assignee: [name: userName],
                       issuetype: [id: 1]]]
```
I haven't added any steps around User yet, will try to add few steps around User functionality soon. 
Hope this helps. Thanks for reporting. 

Note: I am testing currently against JIRA 6.4.13 version.

**Comment by nrayapati** [comment]
Logged a JIRA[1] for this change, this is follow the standard Jenkins practice. Please log JIRAs going forward.  I will be disabling the issues support here. Thanks for understanding. 

[1] https://issues.jenkins-ci.org/browse/JENKINS-44253
