### ISSUE TITLE
Edit fixVersions field of issue broken

### ISSUE THREAD

**Issue by shanekwheeler** [jenkinsci/jira-steps-plugin#8]
Editing the fixVersions field seems to be broken in 1.0.1.
It would also be nice if I could just pass the name of the fixVersion instead of the id. Not sure if that is currently supported.
```
def testIssue = [fields: [fixVersions: [id:12904]]]
jiraEditIssue(idOrKey:'PROJ-5', issue:testIssue)
```

**Comment by nrayapati** [comment]
id should be string, made a non passive change there, its my bad :(. 

```groovy
def testIssue = [fields: [fixVersions: [id:'12904']]]
jiraEditIssue(idOrKey:'PROJ-5', issue:testIssue)
```
JIRA currently doesn't support updates by name, but we could try some alternatives. 

Query the project, which will give us all the fixed versions, then filter the list by name to get version, then we can use that version to update the issue.  I haven't tested but a small example below. 

```groovy
node {
  stage('JIRA') {
    def project = jiraGetProject idOrKey: "TEST"
    def versions = project.data.versions
    def id = 0
    for (i = 0; i <versions.size(); i++) {
      if versions[i].name == 'existing-fix-version'
        id = i
    }
    def testIssue = [fields: [fixVersions: [versions[id]]]]
    response = jiraEditIssue idOrKey: 'TEST-09', issue: testIssue
  }
}
```

Note: I am currently on vacation with limited access to internet. Please expect delay in my response.

**Comment by nrayapati** [comment]
@shanekwheeler were you able to test as suggested above, let me know if you need some more information or I would like to close this issue.

**Comment by thomasbergmann** [comment]
If statement was wrong, but anyway, it fails if there´s no version. It needs an extra check.

```groovy
node {
  stage('JIRA') {
    def project = jiraGetProject idOrKey: "TEST"
    def versions = project.data.versions
    def id = 0
    for (i = 0; i <versions.size(); i++) {
      if (versions[i].name == 'existing-fix-version') {
        id = i
	}
    }
    def testIssue = [fields: [fixVersions: [versions[id]]]]
    response = jiraEditIssue idOrKey: 'TEST-09', issue: testIssue
  }
}
```

**Comment by nrayapati** [comment]
Thanks for correction, as I said I didn't test that example. Since we are querying an existing versions I guess there is no chance of that version being not exist in the system. unless it has been archived. 

Yeah but it is good to check the version if that is being archived before we update the issue in case if you wanted to fail fast or you could catch the exception while updating issue and fail. Either the cases you would fail the job.

**Comment by nrayapati** [comment]
Closing this since the example provided was tested across the other issues from other users already.
