### ISSUE TITLE
Ability to retrieve and update custom fields

### ISSUE THREAD

**Issue by lsim-bravura** [jenkinsci/jira-steps-plugin#9]
Please add the ability to retrieve and update custom fields

**Comment by nrayapati** [comment]
Yes, this is something I thought of doing with initial release but I couldn't. This should be one of the top lists for the next release. Thanks for reporting @lsim-bravura

**Comment by nrayapati** [comment]
Logged a JIRA[1] for this change, this is follow the standard Jenkins practice. Please log JIRAs going forward. I will be disabling the issues support here. Thanks for understanding.

[1] https://issues.jenkins-ci.org/browse/JENKINS-44254
